apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirestnh
spec:
  selector:
    matchLabels:
      app: apirestnh
  replicas: 3
  template:
    metadata:
      labels:
        app: apirestnh
    spec:
      containers:
      - name: apirestnh
        image: msalvadorp/cmtapirest
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080